<?php
require __DIR__.'/vendor/autoload.php';
use LearnositySdk\Request\Init;
use LearnositySdk\Utils\Uuid;

$consumer_key = 'yis0TYCu7U9V4o7M';
$consumer_secret = '74c5fd430cf1242a527f6223aebd42d30464be22';

$security = [
    'consumer_key' => $consumer_key,
    'domain'       => 'localhost'
];

// unset the session id cookie if it is set
if(isset($_COOKIE['session'])) {
    unset($_COOKIE['session']); 
}

$activity_template_id = $_COOKIE['reference'];

echo "activity_template_id: $activity_template_id";

//simple api request object for Items API
$request = [
    'activity_id' => 'itemsassessdemo',
    'activity_template_id' => $activity_template_id,
    'name' => 'Items API demo - assess activity',
    'rendering_type' => 'assess',
    'type' => 'submit_practice',
    'session_id' => Uuid::generate(),
    'user_id' => '$ANONYMIZED_USER_ID',
    'config' => [
        'configuration' => [
            'onsubmit_redirect_url' => './report.php'
        ]
    ]
];


$Init = new Init('items', $security, $consumer_secret, $request);
$signedRequest = $Init->generate();

?>

<!DOCTYPE html>
<html>
<head>
    <title>Items API</title>
</head>
<body>
<div>
    <h2>
        Take your assessment here. After you submit you will see a report generated by Reports API!
    </h2>
    <div id="learnosity_assess"></div>
</div>
<script type="text/javascript" src="https://items.learnosity.com"></script>
<script>

    const callbacks = {
        readyListener: function () {
            console.log("Items API has successfully initialized.");
            itemsApp.on('test:submit:success', () => {
                const session = itemsApp.getActivity().session_id
                console.log('session', session)
                document.cookie = `session=${session}`
            })
        },
        errorListener: function (err) {
            console.log(err);
        }
    };

    const itemsApp = LearnosityItems.init(<?=$signedRequest?>, callbacks);
</script>
</body>
</html>